[build]
base = "."
publish = "dist/"
# Default build command.
command = "yarn generate"

[build.processing.css]
bundle = true
minify = false
[build.processing.js]
bundle = true
minify = false
[build.processing.html]
pretty_urls = true
[build.processing.images]
compress = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[template.environment]
DOMAIN_NAME = "The domain name of your site: (EX: https://example.com)"
ENDPOINT_URL = "The graphql endpoint: (EX: http://mc.example.com/graphql)"
DISCORD_CLIENT_ID = "Your Discord client ID"
DISCORD_CLIENT_SECRET = "Your Discord client secret"
DISCORD_CODE_VERIFIER = "Site Secreit: (A secret string of text, can be random)"
