[template.environment]
DOMAIN_NAME = "The domain name of your site: (EX: https://example.com)"
ENDPOINT_URL = "The graphql endpoint: (EX: http://mc.example.com/graphql)"
DISCORD_CLIENT_ID = "Your Discord client ID"
DISCORD_CLIENT_SECRET = "Your Discord client secret"
DISCORD_CODE_VERIFIER = "Site Secreit: (A secret string of text, can be random)"
