name: Linting

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Linting process
        uses: github/super-linter@v3
        env:
          IGNORE_GITIGNORE_FILES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
